# Gender classification

### exporting essentials libaries and EDA

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# import dataset

df = pd.read_csv('gender_classification_v7.csv')

In [7]:
df.head()

long_hair  forehead_width_cm  forehead_height_cm  nose_wide  nose_long  \
0          1               11.8                 6.1          1          0   
1          0               14.0                 5.4          0          0   
2          0               11.8                 6.3          1          1   
3          0               14.4                 6.1          0          1   
4          1               13.5                 5.9          0          0   

   lips_thin  distance_nose_to_lip_long  gender  
0          1                          1    Male  
1          1                          0  Female  
2          1                          1    Male  
3          1                          1    Male  
4          0                          0  Female

In [4]:
df

long_hair  forehead_width_cm  forehead_height_cm  nose_wide  nose_long  \
0             1               11.8                 6.1          1          0   
1             0               14.0                 5.4          0          0   
2             0               11.8                 6.3          1          1   
3             0               14.4                 6.1          0          1   
4             1               13.5                 5.9          0          0   
...         ...                ...                 ...        ...        ...   
4996          1               13.6                 5.1          0          0   
4997          1               11.9                 5.4          0          0   
4998          1               12.9                 5.7          0          0   
4999          1               13.2                 6.2          0          0   
5000          1               15.4                 5.4          1          1   

      lips_thin  distance_nose_to_lip_long  gender  
0             1                          1    Male  
1             1                          0  Female  
2             1                          1    Male  
3             1                          1    Male  
4             0                          0  Female  
...         ...                        ...     ...  
4996          0                          0  Female  
4997          0                          0  Female  
4998          0                          0  Female  
4999          0                          0  Female  
5000          1                          1    Male  

[5001 rows x 8 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5001 entries, 0 to 5000
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   long_hair                  5001 non-null   int64  
 1   forehead_width_cm          5001 non-null   float64
 2   forehead_height_cm         5001 non-null   float64
 3   nose_wide                  5001 non-null   int64  
 4   nose_long                  5001 non-null   int64  
 5   lips_thin                  5001 non-null   int64  
 6   distance_nose_to_lip_long  5001 non-null   int64  
 7   gender                     5001 non-null   object 
dtypes: float64(2), int64(5), object(1)
memory usage: 312.7+ KB


In [5]:
df['long_hair'].value_counts()

1    4349
0     652
Name: long_hair, dtype: int64

In [6]:
df['forehead_width_cm'].value_counts()

12.0    168
11.8    161
14.1    155
14.0    154
11.5    154
11.6    152
11.9    150
13.3    149
14.2    149
12.2    145
12.6    145
12.1    145
13.2    143
14.3    143
12.9    141
12.5    141
13.7    140
12.8    138
12.3    138
13.6    138
13.0    137
13.4    137
13.5    136
13.8    134
11.7    133
13.1    131
13.9    131
12.7    130
12.4    127
11.4     84
14.9     79
14.5     72
15.2     71
15.5     66
15.1     65
15.4     64
15.3     64
14.4     63
14.6     61
15.0     60
14.7     59
14.8     48
Name: forehead_width_cm, dtype: int64

In [7]:
df['gender'].value_counts()

Female    2501
Male      2500
Name: gender, dtype: int64

In [8]:
# encoding

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['gender'] = le.fit_transform(df['gender'])
df.head()

long_hair  forehead_width_cm  forehead_height_cm  nose_wide  nose_long  \
0          1               11.8                 6.1          1          0   
1          0               14.0                 5.4          0          0   
2          0               11.8                 6.3          1          1   
3          0               14.4                 6.1          0          1   
4          1               13.5                 5.9          0          0   

   lips_thin  distance_nose_to_lip_long  gender  
0          1                          1       1  
1          1                          0       0  
2          1                          1       1  
3          1                          1       1  
4          0                          0       0

# Objective : To predict gender based on essential facial features using different ML algorithms and compare the results

# Method 1: Logestic Regression

## step1: store the feature in X and Target in y

In [9]:
X = df.drop(['gender'],axis =1).values

In [10]:
X

array([[ 1. , 11.8,  6.1, ...,  0. ,  1. ,  1. ],
       [ 0. , 14. ,  5.4, ...,  0. ,  1. ,  0. ],
       [ 0. , 11.8,  6.3, ...,  1. ,  1. ,  1. ],
       ...,
       [ 1. , 12.9,  5.7, ...,  0. ,  0. ,  0. ],
       [ 1. , 13.2,  6.2, ...,  0. ,  0. ,  0. ],
       [ 1. , 15.4,  5.4, ...,  1. ,  1. ,  1. ]])

In [11]:
y= df['gender'].values
y

array([1, 0, 1, ..., 0, 0, 1])

## step 2: split the data into train and test

In [12]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size =0.2)

## step3 : select model(LogesticRegression)

In [13]:
from sklearn.linear_model import LogisticRegression

In [14]:
logReg = LogisticRegression()

## step 4: train the model

In [15]:
logReg.fit(X_train,y_train)

LogisticRegression()

## step 5: test the model (make predictions on the trained model)

In [16]:
y_pred = logReg.predict(X_test)

In [17]:
y_pred

array([0, 1, 0, ..., 0, 1, 0])

In [10]:
df1 = pd.DataFrame({'acctual':y_test, 'predicred':y_pred})

NameError: name 'y_test' is not defined

In [19]:
df1

y_test  y_perd
0          0       0
1          1       1
2          0       0
3          1       0
4          0       0
...      ...     ...
996        1       1
997        1       1
998        0       0
999        1       1
1000       0       0

[1001 rows x 2 columns]

## Check the performance : using, accuracy_score

In [27]:
from sklearn.metrics import accuracy_score, confusion_matrix,r2_score

In [28]:
score = accuracy_score(y_test,y_pred)
print(score)

0.961038961038961


In [30]:
cv = confusion_matrix(y_test,y_pred)
print(cv)

[[478  19]
 [ 20 484]]


In [31]:
r2_score(y_test,y_pred)

0.8441482226693494

#  Method 2 : DecisionTreeClassifier

In [32]:
df.head()

long_hair  forehead_width_cm  forehead_height_cm  nose_wide  nose_long  \
0          1               11.8                 6.1          1          0   
1          0               14.0                 5.4          0          0   
2          0               11.8                 6.3          1          1   
3          0               14.4                 6.1          0          1   
4          1               13.5                 5.9          0          0   

   lips_thin  distance_nose_to_lip_long  gender  
0          1                          1       1  
1          1                          0       0  
2          1                          1       1  
3          1                          1       1  
4          0                          0       0

## step1 : select model

In [41]:
from sklearn.tree import DecisionTreeClassifier

In [46]:
dtc = DecisionTreeClassifier(criterion='entropy',max_depth = 5,random_state=0)

## step 2: train model

In [47]:
dtc.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=5, random_state=0)

## step 3: Test the model : Make predictions on the trained model

In [50]:
y_pred = dtc.predict(X_test)

In [58]:
df2 = pd.DataFrame({'actual':y_test,'predicted':y_pred})

In [59]:
df2.head()

actual  predicted
0       0          0
1       1          1
2       0          0
3       1          0
4       0          0

## step 4: Check the performance : using, accuracy_score,f1_score

In [62]:
from sklearn.metrics import accuracy_score,f1_score,confusion_matrix

In [64]:
score = accuracy_score(y_test,y_pred)
print (score)

0.961038961038961


In [65]:
f1_score(y_test,y_pred)

0.9608040201005026

In [66]:
confusion_matrix(y_test,y_pred)

array([[484,  13],
       [ 26, 478]], dtype=int64)

## Hyper Parameter Tuning

In [72]:
from sklearn.model_selection import GridSearchCV

In [73]:
dtc1 = DecisionTreeClassifier(random_state=0)

In [74]:
params = {'max_depth':list(range(2,50)), 'criterion':['gini', 'entropy']}

In [75]:
cv_gs = GridSearchCV(dtc1, param_grid = params)
cv_gs

GridSearchCV(estimator=DecisionTreeClassifier(random_state=0),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,
                                       14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
                                       24, 25, 26, 27, 28, 29, 30, 31, ...]})

In [76]:
cv_gs.fit(X_train,y_train)

GridSearchCV(estimator=DecisionTreeClassifier(random_state=0),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,
                                       14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
                                       24, 25, 26, 27, 28, 29, 30, 31, ...]})

In [77]:
cv_gs.best_params_

{'criterion': 'entropy', 'max_depth': 7}

In [79]:
dtc_tuned = DecisionTreeClassifier(criterion='entropy', max_depth = 7,random_state=0)

In [82]:
dtc_tuned.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=7, random_state=0)

In [83]:
y_pred = dtc_tuned.predict(X_test)

In [84]:
score = accuracy_score(y_test,y_pred)
print (score)

0.967032967032967


In [85]:
f1_score(y_test,y_pred)

0.9672943508424182

In [86]:
confusion_matrix(y_test,y_pred)

array([[480,  17],
       [ 16, 488]], dtype=int64)